name: Run RS Pipeline Bot

on:
  schedule:
    # Tự động chạy vào lúc 16:00 chiều từ Thứ 2 đến Thứ 6 (Giờ VN là 09:00 UTC)
    - cron: '0 9 * * 1-5'
  workflow_dispatch: # Cho phép bấm nút chạy bằng tay bất cứ lúc nào

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Tắt cảnh báo vàng khó chịu của GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Kéo code từ kho về
      uses: actions/checkout@v4

    - name: Cài đặt Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Nâng cấp lên bản 3.12 chạy cho nhanh

    - name: Cài đặt thư viện
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy gspread oauth2client vnstock==0.2.8.2 tqdm

    - name: Tạo file Chìa khóa từ Secret
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: echo "$GOOGLE_CREDENTIALS" > credentials.json

    - name: Khởi động Bot Cào Data
      run: python rs_worker.py
